UIORGS-343 remove unneeded react-redux
folio-org/ui-organizations pull request #532
Opened 2023-01-24 00:33 UTC by ryandberger

And upgrade `stripes-acq-components` to `v4`

2023-01-25 14:41 UTC, zburke requested changes
The `react-redux` changes LGTM, but the `engines` update should either be removed (preferable) or bumped further all the way to 16.

2023-01-25 14:41 UTC, zburke commented on package.json
> +    "node": ">=14.0.0"
I would either remove `engines` altogether or leave it alone to deal with in a separate PR. Bumping to 14 is ... inadequate: technically, nodejs isn't a runtime dependency at all (hence it should be removed), but if we wanted to capture the dev-requirements than the minimum version to compile translations is v16 due to a transitive dep of `formatjs`.

2023-01-25 14:41 UTC, zburke commented on package.json
> +    "redux": "^4.0.0"
Thanks for cleaning up these `*` deps!

2023-01-26 12:03 UTC, zburke approved these changes

2023-01-28 08:16 UTC, NikitaSedyx approved these changes

2023-01-30 08:21 UTC, usavkov-epam approved these changes

2023-01-30 16:39 UTC, merged